let minecraftItems = [
  {
    "id": "axolotl",
    "title": "Axolotl",
    "price": 25,
    "details": "Axolotls are passive toward players and can be attached to leads. Axolotls give Regeneration I for 100 game ticks (5 seconds) per Axolotl in the fight, up to a duration of 2400 game ticks (2 minutes)?[Java Edition only], and remove Mining Fatigue when a player kills a mob that is in combat with an axolotl. Axolotls attack all aquatic mobs except turtles, dolphins, frogs and other axolotls. They also attack drowned. An axolotl deals 2? points of damage per attack. After killing a non-hostile mob, there is a two minute cooldown before another non-hostile mob can be hunted. Axolotls prioritize attacking hostile mobs over non-hostile mobs. If an axolotl takes damage underwater, it may play dead, dropping to the ground for 200 game ticks (10 seconds) while gaining Regeneration I. Hostile aquatic mobs ignore healing axolotls. There is a 1?3 chance for an axolotl to play dead to recover 4??. In addition, if either a random integer from 02 (inclusive) is less than the amount of incoming damage, or the axolotl's health before the damage is dealt is less than 50% of its maximum health, it plays dead. Axolotls can leave the water and wander about on land. When an axolotl leaves the water, it wanders as far as 8 or 9 blocks beyond the water's edge before returning to the water, as long as there is water at least 2 blocks deep within 16 blocks of the axolotl. If 2-block-deep water is outside this range, the axolotl can wander off randomly on land in search of more deep water, and die after 6000 game ticks (5 minutes) exposure out of water. Axolotls are not attracted to shallow (1 block deep) water. They require water at least 2 blocks deep within 16 blocks to pathfind to the water.[1] Axolotls can also die out of water as passengers in a boat. Unlike fish, dolphins, and squid, axolotls do not die on land in rain or in a thunderstorm. Unlike most mobs, axolotls cannot be moved by flowing water. However, they are still affected by bubble columns. As aquatic mobs, they take extra damage from the Impaling enchantment.?[Java Edition only]?[until JE Edition Combat Tests] Unlike other aquatic mobs, they cause nearby pufferfish to inflate. Axolotls picked up with a water bucket and re-spawned do not despawn. Axolotls can be renamed by placing a bucket of axolotl into an anvil, the same as if renaming any other item."
  },
  {
    "id": "bat",
    "title": "Bat",
    "price": 5,
    "details": "Bats are small, less than a block tall and wide. They squeak randomly. They often fly around aimlessly, tending to favor the east, and sometimes fly into lava and catch on fire. Bats hang upside down on the underside of a solid block when idle, though they cannot hang on transparent or non-solid blocks. If a player approaches a bat hanging upside down, even if the player is invisible, it flies away. This also happens if the player breaks the block the bat is hanging from. Bats despawn when too far away from the player. Bats' collision boxes do not interact with the player or redstone components."
  },
  {
    "id": "cat",
    "title": "Cat",
    "price": 5,
    "details": "Cats can spawn every 1200 ticks (1 minute). A random player is selected (including spectators) and a random location is chosen 8-32 blocks away from the player horizontally in both directions and at the same height. A cat can spawn if that block is less than 2 chunks from a village with fewer than 5 cats, or inside a swamp hut. Villages\nUntamed cats spawn in villages as long as there are at least five claimed beds within 48 blocks and at most four cats within a 971797 box centered around the spawn position. Cats that spawn with the creation of a village do not despawn, however, any additional cats that spawn within a village may despawn. A village cat spawns with a random appearance, although black cats may spawn only during a full moon; which works on both Java and Bedrock][verify]. The spawning of cats in villages is a separate process from the natural spawning of passive mobs and thus is not affected by the Creature mob cap. in Bedrock Edition, a village periodically spawns stray cats to fill a quota of 1 cat per 4 owned beds, up to a maximum of 5 cats for 20 or more owned beds. Only owned beds (those currently claimed by a villager) are counted for this purpose. All cats within the village boundaries are counted, including kittens, cats that wander in from outside and even tamed cats owned by a player. If the number of cats found is short of the quota, the village tries to spawn one cat or kitten within a volume of 16  6  16 blocks centered on the village center. (This is the same volume used when a village spawns an iron golem.) Swamp Hut\nOne untamed black cat generates alongside a witch inside swamp huts upon world generation. This cat never despawns. Additional cats can spawn within the hut similarly to witches. In Java Edition, any other cats to spawn within the witch hut (from spawn eggs and commands without cat type set) always spawn as black. A new cat does not spawn in a hut if there is already a cat within a 16816 block volume.?"
  },
  {
    "id": "chicken",
    "title": "Chicken",
    "price": 5,
    "details": "Chickens spawn naturally in the Overworld in groups of four on grass blocks with 2 blocks of free space above it at a light level of 9 or more. They do not spawn in deserts, snowy plains, ice spikes, snowy slopes, meadows, wooded badlands, jagged peaks, frozen peaks and stony peaks. In Java Edition, chickens are more common in sparse jungles. After the world generation, chickens spawn individually. 5% of chickens spawn as baby chickens. In Bedrock Edition, chickens require a light level of 7 or more to spawn and are found in groups of two to four. Adult chickens that were not part of chicken jockeys lay an egg every five to ten minutes. When an adult chicken is killed, it drops from zero to two feathers. The maximum is increased by one per level of Looting, for a maximum of zero to five with Looting III. The chicken also drops a raw chicken (one cooked chicken if killed while on fire). The maximum is increased by one per level of Looting, for a maximum of one to four with Looting III. 13 experience orbs are dropped when a chicken is killed by a player or tamed wolf or 10 if it was part of a chicken jockey. When two adult chickens breed, 17 orbs are dropped. Killing a baby chicken yields no items or experience."
  },
  {
    "id": "cow",
    "title": "Cow",
    "price": 15,
    "details": "Cows spawn above grass blocks in small herds during world generation or individually afterwards. Their spawn rate varies per biome. In Bedrock Edition, herds of two to three cows spawn on grass blocks at a light level of 9 or higher with at least two blocks of space above, in most grassy biomes except for snowy taigas, snowy plains, meadows, mangrove swamps and wooded badlands. In Java Edition, herds of four cows spawn on grass blocks at a light level of 7 or higher with at least two blocks of space above, in most grassy biomes except for snowy plains, meadows, mangrove swamps and wooded badlands. Also, a cow sometimes spawns inside animal pens and butchers' houses in villages. Shearing a mooshroom turns it into a cow and drops five mushrooms corresponding to the type of mooshroom. Most cows spawn as adults, but they have a 5% chance of spawning as a calf (baby cow). An adult cow drops: 1 to 3 raw beef (or steak if killed while on fire), with a maximum amount is increased by 1 per level of Looting, for a maximum of 6 with Looting III. 0 to 2 leather, with a maximum amount increased by 1 per level of Looting, for a maximum of 5 with Looting III.\n13 experience orbs are dropped when killed by a player or tamed wolf or 17 upon a successful breeding.\nKilling a calf yields no items nor experience. Behavior A calf compared to a cow. A cow moos and huffs occasionally while wandering aimlessly, but tends to stay on well lit and grassy places. A cow also: flees and remains 25% faster for a few seconds when harmed.\nlooks at players within six blocks for two to four seconds sometimes.\navoids going to water unless it is following players and always avoid traversing minecart rails and walking off cliffs high enough to cause fall damage.\navoids environmental hazards, such as cactus, sweet berry bushes, dripstone, fire or lava, but make no attempts to avoid explosions."
  },
  {
    "id": "donkey",
    "title": "Donkey",
    "price": 15,
    "details": "1-3 donkeys spawn in plains and only 1 in savannas. Donkeys also spawn in meadows. 20% of the individual donkeys spawn as foals. Bedrock Edition\n2-6 donkeys spawn only in plains at light level 7 or above.[1] Appearance\nAdult donkeys are 1.4 blocks wide and long, and 1.6 blocks high. Foals start at half the size of adults and in Bedrock Edition, get progressively bigger as they age. Unlike wolves and cats, the appearances of donkeys do not change once they have been tamed, though tamed donkeys may be differentiated by giving them equipment. Donkeys are smaller all around than the normal horses and sport long, erect ears. Their manes do not protrude, but rather are drawn directly on the back of their heads and necks. All donkeys have gray-brown coats with darker ankles, ears, manes, and tails. Donkeys can be equipped with a simple saddle, not the full covered armor and they can also be equipped with chests to store up to 15 stacks of items. Unlike almost all other mobs, donkeys with equipped saddles or chests do not render these when under the effect of Invisibility. [2] Drops\nUpon death, donkeys drop: 02 Leather. The maximum amount is increased by 1 per level of Looting, for a maximum of 0-5 with Looting III.\n13, when killed by a player or tamed wolf.\nIf equipped with a chest or saddle, they drop those items. They also drop the contents of the chest. Upon successful breeding, 17 is dropped. Killing a baby donkey yields no items nor experience. Usage\nTamed and saddled donkeys are some of the fastest means of transportation or hauling in the game, although they are unable to fit through single block-wide openings. They can also be used to climb hills and jump fences, which the player can't generally. They can be ridden in water up to 2 blocks deep. In deeper water, donkeys separate from the player and swim uncontrolled. Donkeys can be equipped with chests and used as pack animals. Donkeys can be pulled along and tied up using a lead, and can be towed, swimming behind a boat by using a lead."
  },
  {
    "id": "fox",
    "title": "Fox",
    "price": 10,
    "details": "Foxes spawn in groups of two to four in taiga, old growth taiga, snowy taiga and grove biomes. 5% of them spawn as baby foxes. They can spawn on grass, coarse dirt, podzol, snow blocks, or top snow. Foxes that spawned in a snowy biome are white. Holding items\nFoxes have a 20% chance to spawn (via spawn egg or naturally)\nDrops\nAn adult fox drops 12?[JE only]/13?[BE only] experience orbs when killed by a player or tamed wolf. Upon successful breeding, 17 are dropped. Killing a baby fox yields no experience. Foxes always drop any item they pick up and are still holding (they cannot drop food that they have eaten, for example) and drop items they spawn with naturally with a 100% chance, so:"
  },
  {
    "id": "frog",
    "title": "Frog",
    "price": 5,
    "details": "A frog is a passive mob found in swamps. Frogs eat small slimes and magma cubes. A frog can produce one of three kinds of Froglights from eating magma cubes, depending on the type of frog.\nGroups of two to five frogs can spawn in swamp and mangrove swamp biomes. Frogs can also be spawned by growing from tadpoles. There are three frog variants, determined by the biome in which the tadpole grew up:\nDrops\nFrogs drop 13 when killed by a player or tamed wolf, while 17 is dropped upon successful breeding. Behavior\nOn land, frogs will slowly wander, jumping at random. They can jump 8 blocks high and take 10????? less damage from falling than most other mobs. They prefer jumping on lily pads and big dripleaves, and will usually jump to blocks that are higher up. As with other mobs, honey blocks will stop frogs from jumping. In water, frogs move much faster. They will generally swim upwards and remain at the water's surface, but will swim downwards if lured by a player. Frogs cannot be hurt by drowning. Occasionally, they may croak and inflate their vocal sac. However, the inflation of their vocal sac doesn't always mean they are croaking. But their croaking always means the inflation of the vocal sac. Breeding\nFrogs will follow any player holding a slimeball within 6 blocks of them. Feeding two frogs a slimeball causes them to enter love mode, causing one of the frogs to become pregnant, similar to turtles. The pregnant frog then searches for a water block with at least one adjacent water block (flowing or source) with air above to lay frogspawn. This spawn later hatches into tadpoles, which subsequently grow into frogs. Unlike all other mobs with baby variants, the tadpole is treated by the game as a completely different mob from the frog."
  },
  {
    "id": "horse",
    "title": "Horse",
    "price": 20,
    "details": "Horses spawn in plains and savannas in herds of 26. For horses, all combinations of color and markings are equally likely. All members of the herd have the same color, but markings may vary. 20% of all individual horses spawn as foals. Villages naturally generate with stables and animal pens containing horses. Appearance All 35 colorations of horses. Base colors, from left to right: white, buckskin, flaxen chestnut, bay, black, dapple gray, and dark bay. Markings, from top to bottom: none, stockings and blaze, paint, snowflake appaloosa, and sooty. Each horse variant has unique features and markings, and a foal (baby) version. Adult horses are 1.4 blocks wide and long, and 1.6 blocks high. Foals start at half the size of adults, and in Bedrock Edition, get progressively bigger as they age. Unlike wolves and cats, the appearances of horses do not change once they have been tamed, though tame horses may be differentiated by giving them equipment. Horses have a stocky build. They can have 1 of 7 base colors: white, buckskin, flaxen chestnut, bay, black, dapple gray, and dark bay; and 1 of 5 marking patterns: no markings, stockings and blaze, paint, snowflake appaloosa and sooty. In total, there are 35 possible horse coat combinations. Unlike almost all other mobs, horses with equipped saddles don't render these when under the effect of Invisibility."
  },
  {
    "id": "mooshroom",
    "title": "Mooshroom",
    "price": 25,
    "details": "Red mooshrooms can spawn in mushroom fields biomes in herds of 48 when the light level is 9 or higher and on mycelium. They do not naturally spawn in any other biome. A red mooshroom transforms into a brown mooshroom (and vice versa) when it is struck by lightning. Brown mooshrooms never spawn naturally. Red mooshrooms have a 5% chance of spawning as babies. Breeding\nMain article: Breeding\nA pair of mooshrooms can breed after being given wheat. A mooshroom cannot be bred with a cow unless the mooshroom has been sheared. Feeding wheat to a calf shortens its growing time by 10% of the remaining time. Baby mooshrooms do not have mushrooms on their backs. Mushrooms appear once the baby grows to an adult. Breeding two red mooshrooms has a 1?1024 chance to spawn a brown baby variant and vice versa. When breeding a red mooshroom and a brown mooshroom together, there is 1?2 chance of getting a red baby variant, and a 1?2 chance of getting a brown baby variant."
  },
  {
    "id": "mule",
    "title": "Mule",
    "price": 20,
    "details": "Mules do not spawn naturally, but they can spawn through cross-breeding a horse with a donkey. Mules cannot breed with other mules. 20% of mule spawn eggs produce foals. Appearance\nMules are the offspring of horses and donkeys and are closer to (but not quite) the size of a normal horse. Their ears, coats, and manes are like those of a donkey, though mules' coats are darker and reddish-brown. Like donkeys, mules cannot be equipped with armor but can be equipped with chests. Mules cannot have foals, much like mules in real life. Unlike almost all other mobs, mules with equipped saddles or chests do not render them when under the effect of Invisibility.[1] Drops\nUpon death, mules drop: 02 Leather. The maximum amount is increased by 1 per level of Looting, for a maximum of 0-5 with Looting III.\n13, when killed by a player or tamed wolf.\nIf equipped with a chest or saddle, they drop those items, as well as any contents of the chest."
  },
  {
    "id": "ocelot",
    "title": "Ocelot",
    "price": 30,
    "details": "Ocelots spawn above grass blocks at sea level (y=63 per default) or higher in groups of 1 or 2. These are mostly adults but sometimes ocelots spawn as kittens. When an adult ocelot spawns, there is a 1?7 (14.3%) chance for 2 ocelot kittens to spawn with it; this chance only includes spawning naturally. Java Edition\nThere is a 1?3 chance for a spawn attempt to fail in jungles, and spawning always fails in bamboo jungles or sparse jungles. While ocelots are passive mobs, they count towards the hostile mob cap, meaning they cannot spawn at all on Peaceful difficulty.[2] Bedrock Edition\nOcelots are found in all kinds of jungles. Drops\nUpon death, adult ocelots drop 13 when killed by a player or tamed wolf. Upon successful breeding, 17 is dropped. Like other baby animals, killing a baby ocelot yields no experience."
  },
  {
    "id": "parrot",
    "title": "Parrot",
    "price": 6,
    "details": "Parrots are passive. They can fly, and usually fly upward if struck. They fly under normal conditions, but they can tire[1] and return to the ground. Parrots crowd and settle around other nearby mobs, including neutral and hostile mobs. When in water, a parrot swims by flapping its wings. Like chickens, parrots flap their wings and fall slowly, preventing fall damage. Taming\nParrots can be tamed by feeding them wheat seeds, melon seeds, pumpkin seeds, or beetroot seeds, with 1?10 chance of success. Once tamed, interacting with a parrot makes it sit down and stand up. Like tamed wolves and cats, a tamed parrot follows the player unless told to sit, and may teleport if there is a sufficient distance between them and the player. Like all tamed animals upon death, a death message is displayed to its owner. Parrot teleportation is completely silent.[2] Unlike most animals, parrots have no baby form, and cannot be bred."
  },
  {
    "id": "pig",
    "title": "Pig",
    "price": 8,
    "details": "5% of pigs spawn as piglets, and 95% of pigs spawn as adults. Pigs cannot spawn naturally with a saddle. Villages\nIn villages, pigs spawn in animal pens, stables and in butcher house backyards. Natural generation\nJava Edition\nPigs spawn in groups of 4 above grass blocks at a light level of 9 or more in any grassy Overworld biome except in snowy plains, meadows and wooded badlands. Individuals rarely may spawn on grass after the world generation. Bedrock Edition\nPigs spawn in groups of 1-3 above grass blocks at a light level of 7 or more in any grassy Overworld biome except in snowy tundras and wooded badlands plateaus. Individuals regularly spawn on grass after the world generation. Drops\nAn adult pig drops: 13 raw porkchop or cooked porkchop if killed while on fire. The maximum amount is increased by 1 per level of Looting, for a maximum of 1-6 with Looting III.\n1 saddle if saddled\n13 if killed by a player or tamed wolf\n17 upon breeding\nKilling a piglet yields no items nor experience."
  },
  {
    "id": "rabbit",
    "title": "Rabbit",
    "price": 5,
    "details": "Creamy rabbits are the most common rabbit color and are found only in deserts and its variants. White and black and white rabbits are also quite common and spawn in snowy biomes such as snowy taigas, snowy plains, groves and snowy slopes. Default rabbit colors such as brown, black and salt and pepper spawn naturally in flower forests, taigas and meadows, but can also spawn in any other non-snowy biome via spawn eggs, commands, spawners or breeding. In all these places, groups of an adult and one to two babies spawn. In Bedrock Edition, up to three kits spawn in flower forests and rabbits can also spawn in frozen aquatic biomes: snowy beaches, frozen oceans, and frozen rivers. In Java Edition, rabbits can also be found in giant tree taigas. In taigas, wolves and foxes are also found. If left alone, these may quickly kill rabbits, so rabbits are generally more plentiful in the desert, flowery or icy biomes. The Killer Bunny does not spawn naturally and must instead be spawned using the /summon command, although it is exclusive to Java Edition."
  },
  {
    "id": "sheep",
    "title": "Sheep",
    "price": 8,
    "details": "The majority of sheep are white, with an 81.836% chance of spawning. The light gray, gray and black sheep each have a 5% chance of spawning, or a 15% chance collectively. Brown sheep have an uncommon 3% chance to spawn. Pink sheep have a rare chance of 0.164% of spawning naturally. The majority of sheep are white, with an 81.836% chance of spawning. The light gray, gray and black sheep each have a 5% chance of spawning, or a 15% chance collectively. Brown sheep have an uncommon 3% chance to spawn. Pink sheep have a rare chance of 0.164% of spawning naturally."
  },
  {
    "id": "turtle",
    "title": "Turtle",
    "price": 16,
    "details": "Turtles spawn on the sand in the Overworld on beaches with daylight, but not in its snowy variant or stony shores, occasionally in small groups of up to 5 individuals. 10% of turtles spawned are babies. In Java Edition, turtles spawn at light levels greater than 8, on sand blocks less than 4 blocks above sea level (typically at Y=62). In Bedrock Edition, turtles spawn in groups of 26, at light level 7 or higher, at Y=6067. Drops\nWhen turtles die, they drop: 02 seagrass. The maximum amount is increased by 1 per level of Looting, for a maximum of 05 with Looting III.\n13, if killed by a player or tamed wolf.\n1 bowl, if killed by lightning.[1]\nBaby turtles do not drop anything when they die. When a baby turtle grows up to an adult it drops: 1 scute\nUpon successful breeding, 17 is dropped. Behavior\nTurtles can both move around on land and swim in water. They move slowly on land, but they can swim at a fast speed in the water. Like other passive mobs, they move around aimlessly and flee when attacked. When on land, they generally attempt to move to the nearest water source with direct sky access.[verify] When in an enclosed area, such as a player-made enclosure, they generally swim in circles if the water is in the area, and rarely go on land to explore, if there is any. Turtles cannot be attached to leads,[2] but they can be led by a player holding seagrass within 10 blocks of the turtle. Turtles can be picked up by boats?[Java Edition only] and minecarts. Turtles are killed instantly when struck by lightning. As with other aquatic mobs, turtles suffer extra damage when hit by a trident with the Impaling enchantment,?[Java Edition only]?[until JE Edition Combat Tests] and cannot drown, despite the fact that real-life turtles breathe air."
  }
]

export default minecraftItems;